baseURL = 'https://szymonprz.github.io'
languageCode = 'en-us'
title = 'software dev struggles'
theme = 'PaperMod'

enableEmoji = true

[params]
ShowShareButtons = true
ShowReadingTime = true
defaultTheme = "dark"

[params.editPost]
URL = "https://github.com/szymonprz/szymonprz.github.io/content"
Text = "Suggest Changes"
appendFilePath = true # to append file path to Edit link

[params.homeInfoParams]
Title = "Read some stories about what makes my life as a software dev easier (and sometimes harder)"
Content = """Read about how I try to make my life of software dev easier, or how I try to survive here, maybe it will help you too
- If you like it, do give a 🌟 on [Github](https://github.com/szymonprz/szymonprz.github.io)!"""

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/3474594/szymon-prz"

[[params.socialIcons]]
name = "linkedin"
url = "https://pl.linkedin.com/in/szymon-przebierowski"

[[params.socialIcons]]
name = "email"
url = "mailto:szymonprz@gmail.com"
